Repository InfinityRuby/InfinityCode, pull requests merged in 2021-06, with the labels that each got.

#99 修改: 調整題目及提示的關聯性 (#95)
  app/controllers/api/v1/prompts_controller.rb
  app/models/prompt.rb
  app/models/quest.rb
  config/routes.rb
  db/migrate/20210517064948_create_prompts.rb
  db/schema.rb
Labels: 功能優化

#101 修改: API - 討論區 - 搜尋、分頁、作者資訊 (#89)
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/posts_controller.rb
  app/models/comment.rb
  app/models/post.rb
  app/views/api/v1/posts/index.json.jbuilder
  app/views/api/v1/posts/show.json.jbuilder
  config/routes.rb
Labels: 功能優化

#111 修改: 問題除蟲 - posts/index.json.jbuilder 找不到 user 此方法 (#108)
  app/views/api/v1/posts/index.json.jbuilder
Labels: 問題除蟲

#135 修改: 解題頁面送出答案後，僅呈現 loading 動畫，並無出現答案正確與否的訊息 (#121)
  app/controllers/api/v1/quests_controller.rb
  app/services/docker_service.rb
  db/seeds.rb
Labels: 問題除蟲

#141 修改: API 模組 - 討論區模組 - 新增頁數的 JSON 欄位 (#140)
  app/views/api/v1/posts/index.json.jbuilder
  app/views/api/v1/posts/show.json.jbuilder
Labels: 功能優化

#188 修改: API 模組 - 討論區列表 - 搜尋功能 SyntaxError 錯誤修正 (#187)
  app/views/api/v1/posts/index.json.jbuilder
Labels: 問題除蟲

#205 新增: 獎章模組 - 金幣收集 & 排行榜 (#189)
  app/models/answer.rb
  app/models/post.rb
  app/models/profile.rb
  app/models/user.rb
Labels: 功能開發

#221 新增: transaction 功能(#215)
  db/seeds.rb
Labels: 問題除蟲

#226 修改: API 模組 - 單篇貼文頁面 - 留言排序 (#204)
  app/views/api/v1/posts/show.json.jbuilder
Labels: 問題除蟲

#234 修改: 調整登入後首頁文章列表異常 & 排行榜判斷
  app/javascript/pages/discuss.js
  app/views/api/v1/ranks/likes.json.jbuilder
  app/views/api/v1/ranks/solved.json.jbuilder
Labels: 問題除蟲

#249 修改: postcss.config.js 編輯器被過濾 bug (#240)
  postcss.config.js
  tailwind.config.js
Labels: 問題除蟲

#256 修改: 解題區 - 編輯器會有重複出現的狀況 (#159)
  app/javascript/quest/question.js
Labels: 問題除蟲

#257 修改: 移除purgeCSS套件 & 調整首頁 JS 語法判斷條件
  app/javascript/pages/discuss.js
  package.json
  yarn.lock
Labels: 問題除蟲

#261 修改: CodeMirror 重複出現問題
  app/javascript/quest/question.js
Labels: 問題除蟲

#269 修改: 程式編輯器 JS 語法調整
  app/javascript/quest/question.js
  app/views/api/v1/posts/index.json.jbuilder
  app/views/api/v1/quests/show.json.jbuilder
Labels: 問題除蟲
